[package]
name = "gitpp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
inquire = "0.7.5"
strum =  { version = "0.26.3", features = ["derive"] }
